src/main/java/com/andaily/zhishifenzi/domain/dto/stadium/StadiumDto.java
package com.andaily.zhishifenzi.domain.dto.stadium;

import com.andaily.zhishifenzi.domain.dto.AbstractDto;
import com.andaily.zhishifenzi.domain.stadium.Stadium;

import java.util.ArrayList;
import java.util.List;

/**
 * 14-3-17 下午9:52
 *
 * @author Shengzhao Li
 */
public class StadiumDto extends AbstractDto {

    //球场名称
    protected String name;
    //地址
    protected String address;
    //是否为主场
    protected boolean homeStadium;
    //联系人信息
    protected String contact;
    //备注
    protected String remark;

    public StadiumDto() {
    }

    public StadiumDto(Stadium stadium) {
        super(stadium.guid());
        this.name = stadium.name();
        this.address = stadium.address();

        this.homeStadium = stadium.homeStadium();
        this.contact = stadium.contact();
        this.remark = stadium.remark();
    }

    public String getName() {
        return name;
    }

    public String getNameIncludeHome() {
        if (homeStadium) {
            return name + " (主)";
        }
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public boolean isHomeStadium() {
        return homeStadium;
    }

    public void setHomeStadium(boolean homeStadium) {
        this.homeStadium = homeStadium;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getRemark() {
        return remark;
    }

    public String getShortRemark() {
        if (remark != null && remark.length() > 20) {
            return remark.substring(0, 20) + "...";
        }
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public static List<StadiumDto> toDtos(List<Stadium> stadiums) {
        List<StadiumDto> dtos = new ArrayList<>(stadiums.size());
        for (Stadium stadium : stadiums) {
            dtos.add(new StadiumDto(stadium));
        }
        return dtos;
    }
}

src/main/java/com/andaily/zhishifenzi/domain/dto/stadium/StadiumListDto.java
package com.andaily.zhishifenzi.domain.dto.stadium;

import com.andaily.zhishifenzi.domain.shared.paginated.DefaultPaginated;
import org.apache.commons.lang.StringUtils;

import java.util.Map;

/**
 * 14-3-17 下午10:07
 *
 * @author Shengzhao Li
 */
public class StadiumListDto extends DefaultPaginated<StadiumDto> {

    private String name;

    public StadiumListDto() {
    }

    @Override
    public Map<String, Object> queryMap() {
        Map<String, Object> map = super.queryMap();
        map.put("name", StringUtils.isEmpty(name) ? null : "%" + name + "%");
        return map;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

src/main/java/com/andaily/zhishifenzi/web/controller/backend/BackendController.java
package com.andaily.zhishifenzi.web.controller.backend;

import com.andaily.zhishifenzi.domain.dto.BackendIndexDto;
import com.andaily.zhishifenzi.domain.dto.album.AlbumListDto;
import com.andaily.zhishifenzi.domain.dto.club.ClubListDto;
import com.andaily.zhishifenzi.domain.dto.file.HeadImageUploadDto;
import com.andaily.zhishifenzi.domain.dto.match.*;
import com.andaily.zhishifenzi.domain.dto.player.PlayerListDto;
import com.andaily.zhishifenzi.domain.dto.stadium.StadiumListDto;
import com.andaily.zhishifenzi.infrastructure.DateUtils;
import com.andaily.zhishifenzi.service.*;
import com.andaily.zhishifenzi.web.utils.WebUtils;
import net.sf.json.JSONObject;
import net.sf.json.util.JSONUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletResponse;

/**
 * 14-3-12 下午10:55
 *
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("/b/")
public class BackendController {

    @Autowired
    private MatchService matchService;
    @Autowired
    private SeasonService seasonService;
    @Autowired
    private ClubService clubService;
    @Autowired
    private StadiumService stadiumService;
    @Autowired
    private PlayerService playerService;
    @Autowired
    private AlbumService albumService;
    @Autowired
    private UserService userService;


    @RequestMapping("index.zsfz")
    public String index(Model model) {
        BackendIndexDto indexDto = userService.loadBackendIndexDto();
        model.addAttribute("indexDto", indexDto);
        return "backend/b_index";
    }


    @RequestMapping("my_data.zsfz")
    public String myData(Model model) {
        MyDataDto dataDto = matchService.loadMyDataDto();
        model.addAttribute("dataDto", dataDto);
        return "backend/my_data";
    }

    @RequestMapping("my_match.zsfz")
    public String myMatch(MyMatchesDto matchesDto, Model model) {
        matchesDto = matchService.loadMyMatchesDto(matchesDto);
        model.addAttribute("matchesDto", matchesDto);
        return "backend/my_match";
    }

    @RequestMapping("match.zsfz")
    public String match(MatchListDto listDto, Model model) {
        listDto = matchService.loadMatchListDto(listDto);
        model.addAttribute("listDto", listDto);
        model.addAttribute("today", DateUtils.toDateText(DateUtils.now()));
        return "backend/b_match";
    }

    @RequestMapping("club.zsfz")
    public String club(ClubListDto listDto, Model model) {
        listDto = clubService.loadClubListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "backend/b_club";
    }

    @RequestMapping("album.zsfz")
    public String album(AlbumListDto listDto, Model model) {
        listDto = albumService.loadAlbumListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "backend/b_album";
    }

    @RequestMapping("player.zsfz")
    public String player(PlayerListDto listDto, Model model) {
        listDto = playerService.loadPlayerListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "backend/b_player";
    }

    @RequestMapping("stadium.zsfz")
    public String stadium(StadiumListDto listDto, Model model) {
        listDto = stadiumService.loadStadiumListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "backend/b_stadium";
    }

    @RequestMapping("season.zsfz")
    public String season(SeasonListDto listDto, Model model) {
        listDto = seasonService.loadSeasonListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "backend/b_season";
    }

    @RequestMapping("match_notice.zsfz")
    public String matchNotice(MatchNoticeListDto listDto, Model model) {
        listDto = matchService.loadMatchNoticeListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "backend/b_match_notice";
    }


    @RequestMapping(value = "upload_head_image.zsfz", method = RequestMethod.POST)
    public void upload(HttpServletResponse response, HeadImageUploadDto uploadDto) {
        String fileGuid = userService.saveHeadImageUploadDto(uploadDto);
        WebUtils.writeJson(response, JSONObject.fromObject("{fileGuid:'" + fileGuid + "'}"));
    }

    @RequestMapping(value = "submit_head_image.zsfz", method = RequestMethod.POST)
    public String submitHeadImage(HeadImageUploadDto uploadDto, Model model) {
        userService.persistCropHeadImage(uploadDto);
        return "redirect:index.zsfz";
    }

}

src/main/java/com/andaily/zhishifenzi/web/controller/backend/ClubController.java
package com.andaily.zhishifenzi.web.controller.backend;

import com.andaily.zhishifenzi.domain.dto.club.ClubFormDto;
import com.andaily.zhishifenzi.domain.dto.club.ClubRecordDto;
import com.andaily.zhishifenzi.service.ClubService;
import com.andaily.zhishifenzi.web.validator.ClubFormDtoValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * 14-3-16 下午10:00
 *
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("/b/club/")
public class ClubController {

    @Autowired
    private ClubService clubService;


    @RequestMapping("archive/{guid}.zsfz")
    public String archive(@PathVariable("guid") String guid, Model model) {
        clubService.archiveClub(guid);
        model.addAttribute("alert", "archiveFinishInfo");
        return "redirect:../../club.zsfz";
    }

    @RequestMapping("record.zsfz")
    public String record(ClubRecordDto recordDto, Model model) {
        recordDto = clubService.loadClubRecordDto(recordDto);
        model.addAttribute("recordDto", recordDto);
        return "backend/club/club_record";
    }


}

src/main/java/com/andaily/zhishifenzi/web/controller/backend/ClubFormController.java
package com.andaily.zhishifenzi.web.controller.backend;

import com.andaily.zhishifenzi.domain.dto.club.ClubFormDto;
import com.andaily.zhishifenzi.service.ClubService;
import com.andaily.zhishifenzi.web.validator.ClubFormDtoValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * 14-3-16 下午10:00
 *
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("/b/club/form/{guid}.zsfz")
public class ClubFormController {

    @Autowired
    private ClubService clubService;
    @Autowired
    private ClubFormDtoValidator validator;

    @RequestMapping(method = RequestMethod.GET)
    public String showForm(@PathVariable("guid") String guid, Model model) {
        ClubFormDto formDto = clubService.loadClubFormDto(guid);
        model.addAttribute("formDto", formDto);
        return "backend/club/club_form";
    }


    @RequestMapping(method = RequestMethod.POST)
    public String submit(@ModelAttribute("formDto") ClubFormDto formDto, Model model, BindingResult result) {
        validator.validate(formDto, result);
        if (result.hasErrors()) {
            return "backend/club/club_form";
        }
        clubService.persistClubFormDto(formDto);
        model.addAttribute("alert", "persistSuccess");
        return "redirect:../../club.zsfz";
    }

}

src/main/java/com/andaily/zhishifenzi/web/controller/backend/PlayerAccountFormController.java
package com.andaily.zhishifenzi.web.controller.backend;

import com.andaily.zhishifenzi.domain.dto.player.PlayerAccountDto;
import com.andaily.zhishifenzi.domain.dto.player.PlayerFormDto;
import com.andaily.zhishifenzi.service.PlayerService;
import com.andaily.zhishifenzi.web.validator.PlayerAccountDtoValidator;
import com.andaily.zhishifenzi.web.validator.PlayerFormDtoValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * 14-4-15 下午10:00
 *
 * @author Shengzhao Li
 */
@Controller
//player guid
@RequestMapping("/b/player/account/{playerGuid}.zsfz")
public class PlayerAccountFormController {

    @Autowired
    private PlayerService playerService;
    @Autowired
    private PlayerAccountDtoValidator validator;

    @RequestMapping(method = RequestMethod.GET)
    public String showForm(@PathVariable("playerGuid") String playerGuid, Model model) {
        PlayerAccountDto formDto = playerService.loadPlayerAccountDto(playerGuid);
        model.addAttribute("formDto", formDto);
        return "backend/player/player_account_form";
    }


    @RequestMapping(method = RequestMethod.POST)
    public String submit(@ModelAttribute("formDto") PlayerAccountDto formDto, Model model, BindingResult result) {
        validator.validate(formDto, result);
        if (result.hasErrors()) {
            return "backend/player/player_account_form";
        }
        String guid = playerService.persistPlayerAccountDto(formDto);
        model.addAttribute("alert", "persistSuccess");
        return "redirect:" + guid + ".zsfz";
    }

}

src/main/java/com/andaily/zhishifenzi/web/controller/backend/PlayerController.java
package com.andaily.zhishifenzi.web.controller.backend;

import com.andaily.zhishifenzi.domain.dto.match.PlayerDataDto;
import com.andaily.zhishifenzi.domain.user.UserStatus;
import com.andaily.zhishifenzi.service.PlayerService;
import com.andaily.zhishifenzi.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * 14-3-21 下午9:01
 *
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("/b/player/")
public class PlayerController {

    @Autowired
    private PlayerService playerService;


    @RequestMapping("archive/{guid}.zsfz")
    public String archive(@PathVariable("guid") String guid, Model model) {
        playerService.archivePlayer(guid);
        model.addAttribute("alert", "archiveFinishInfo");
        return "redirect:../../player.zsfz";
    }

    @RequestMapping("account/disable/{guid}.zsfz")
    public String disablePlayerUser(@PathVariable("guid") String guid, Model model) {
        String playerGuid = playerService.changePlayerUserStatus(guid, UserStatus.DISABLED);
        model.addAttribute("alert", "disableFinishInfo");
        return "redirect:../" + playerGuid + ".zsfz";
    }

    @RequestMapping("account/enable/{guid}.zsfz")
    public String enablePlayerUser(@PathVariable("guid") String guid, Model model) {
        String playerGuid = playerService.changePlayerUserStatus(guid, UserStatus.ENABLED);
        model.addAttribute("alert", "enableAccountSuccess");
        return "redirect:../" + playerGuid + ".zsfz";
    }


    //reset password
    @RequestMapping("account/reset_password/{guid}.zsfz")
    public String reset(@PathVariable("guid") String guid, Model model) {
        String newPass = playerService.resetPlayerUserPassword(guid);
        model.addAttribute("newPass", newPass);
        return "backend/player/reset_password_ok";
    }


    //data
    @RequestMapping("data_{guid}.zsfz")
    public String data(@PathVariable("guid") String guid, Model model) {
        PlayerDataDto dataDto = playerService.loadPlayerDataDto(guid);
        model.addAttribute("dataDto", dataDto);
        return "backend/player/player_data";
    }
}

src/main/java/com/andaily/zhishifenzi/web/controller/backend/PlayerFormController.java
package com.andaily.zhishifenzi.web.controller.backend;

import com.andaily.zhishifenzi.domain.dto.player.PlayerFormDto;
import com.andaily.zhishifenzi.service.PlayerService;
import com.andaily.zhishifenzi.web.validator.PlayerFormDtoValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * 14-3-16 下午10:00
 *
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("/b/player/form/{guid}.zsfz")
public class PlayerFormController {

    @Autowired
    private PlayerService playerService;
    @Autowired
    private PlayerFormDtoValidator validator;

    @RequestMapping(method = RequestMethod.GET)
    public String showForm(@PathVariable("guid") String guid, Model model) {
        PlayerFormDto formDto = playerService.loadPlayerFormDto(guid);
        model.addAttribute("formDto", formDto);
        return "backend/player/player_form";
    }


    @RequestMapping(method = RequestMethod.POST)
    public String submit(@ModelAttribute("formDto") PlayerFormDto formDto, Model model, BindingResult result) {
        validator.validate(formDto, result);
        if (result.hasErrors()) {
            return "backend/player/player_form";
        }
        playerService.persistPlayerFormDto(formDto);
        model.addAttribute("alert", "persistSuccess");
        return "redirect:../../player.zsfz";
    }

}

src/main/webapp/WEB-INF/jsp/backend/stadium/stadium_form.jsp

<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE html>
<html>
<head>
    <title>球场</title>
</head>
<body>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-warning">
            <div class="panel-body">
                <form:form commandName="formDto" role="form">
                    <form:hidden path="existName"/>
                    <div class="form-group">
                        <label for="name" class="control-label">球场名称</label>
                        <form:input path="name" cssClass="form-control" id="name" placeholder="请输入球场名称"
                                    required="required"/>
                        <form:errors path="name" cssClass="text-danger"/>
                        <p class="help-block">球场名称必须唯一.</p>
                    </div>
                    <div class="form-group">
                        <label for="contact" class="control-label">联系人</label>
                        <form:input path="contact" cssClass="form-control" id="contact" placeholder="请输入联系人"
                                    required="required"/>
                        <form:errors path="contact" cssClass="text-danger"/>
                        <p class="help-block">该球场的联系人信息, 如: '李四 13300231117(手机) 87658767(QQ号)'.</p>
                    </div>
                    <div class="form-group">
                        <label for="address" class="control-label">球场地址</label>
                        <form:input path="address" cssClass="form-control" id="address" placeholder="请输入球场地址"
                                    required="required"/>
                        <form:errors path="address" cssClass="text-danger"/>
                        <p class="help-block">球场的具体位置.</p>
                    </div>
                    <div class="checkbox">
                        <label>
                            <form:checkbox path="homeStadium"/> 是否为我们的主场
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="remark" class="control-label">备注信息</label>
                        <form:textarea path="remark" id="remark" class="form-control" rows="3"
                                       placeholder="关于该球场的其他信息, 在这儿输入."/>
                        <form:errors path="remark" cssClass="text-danger"/>
                        <p class="help-block">球场的其他信息.</p>
                    </div>

                    <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> 保存
                    </button>
                    &nbsp;<a href="../../stadium.zsfz">取消</a>

                </form:form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/backend/stadium/stadium_record.jsp

<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="dis" uri="http://displaytag.sf.net" %>
<!DOCTYPE html>
<html>
<head>
    <title>比赛纪录</title>
</head>
<body>
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><i class="glyphicon glyphicon-info-sign"></i>
                <span>我们在 <strong>${recordDto.stadiumDto.name}</strong> 踢了 ${recordDto.totalSize} 场比赛.
                        <c:if test="${recordDto.stadiumDto.homeStadium}">
                            <span class="glyphicon glyphicon-heart" title="我们的主场"></span>
                        </c:if>
                </span>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <dis:table id="n" class="table table-striped table-hover" list="${recordDto}"
                       requestURI="">
                <dis:column title="比赛时间" property="matchTime"/>
                <dis:column title="比分">
                    <c:if test="${n.homeScores > n.awayScores}">
                        <strong class="text-danger">${n.homeScores}:${n.awayScores}</strong>
                    </c:if>
                    <c:if test="${n.homeScores eq n.awayScores}">
                        <strong class="text-muted">${n.homeScores}:${n.awayScores}</strong>
                    </c:if>
                    <c:if test="${n.homeScores < n.awayScores}">
                        <strong class="text-warning">${n.homeScores}:${n.awayScores}</strong>
                    </c:if>
                </dis:column>
                <dis:column title="进球(助攻)" property="goalPlayerNames" style="width:40%;"/>
                <dis:column title="球场">
                    ${n.stadium.name} ${n.stadium.homeStadium?'(主)':''}
                </dis:column>
                <dis:column title="赛季" property="season.name"/>
                <dis:column title="备注">
                    <i title="五人制足球赛"
                       class="text-danger ${n.futsal?'glyphicon glyphicon-star-empty':''}"></i> <span
                        title="${n.remark}">${n.shortRemark}</span>
                </dis:column>
            </dis:table>
        </div>
        <div class="text-center">
            <a href="../stadium.zsfz" class="btn btn-success">&laquo; 返回</a>
        </div>
    </div>
</div>

</body>
</html>