src/main/java/com/andaily/zhishifenzi/domain/user/UserStatus.java
package com.andaily.zhishifenzi.domain.user;

/**
 * @author Shengzhao Li
 */

public enum UserStatus {

    ENABLED("启用"),
    DISABLED("禁用");

    private String label;

    private UserStatus(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }

    public String getValue() {
        return name();
    }

    public boolean isEnabled() {
        return ENABLED.equals(this);
    }

    public boolean isDisabled() {
        return DISABLED.equals(this);
    }
}

src/main/java/com/andaily/zhishifenzi/web/controller/user/ChangePasswordController.java
package com.andaily.zhishifenzi.web.controller.user;

import com.andaily.zhishifenzi.domain.dto.user.ChangePasswordDto;
import com.andaily.zhishifenzi.service.UserService;
import com.andaily.zhishifenzi.web.validator.ChangePasswordDtoValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("/b/change_password.zsfz")
public class ChangePasswordController {


    @Autowired
    private UserService userService;
    @Autowired
    private ChangePasswordDtoValidator validator;

    @RequestMapping(method = RequestMethod.GET)
    public String setupForm(Model model) {
        ChangePasswordDto changePasswordDto = userService.loadChangePasswordDto();
        model.addAttribute("changePasswordDto", changePasswordDto);
        return "change_password";
    }


    @RequestMapping(method = RequestMethod.POST)
    public String submit(@ModelAttribute("changePasswordDto") ChangePasswordDto changePasswordDto, BindingResult result) {
        validator.validate(changePasswordDto, result);
        if (result.hasErrors()) {
            return "change_password";
        }
        userService.changePassword(changePasswordDto);
        return "redirect:../signout?pass=true";
    }

}

src/main/java/com/andaily/zhishifenzi/web/controller/user/MyProfileController.java
package com.andaily.zhishifenzi.web.controller.user;


import com.andaily.zhishifenzi.domain.dto.user.MyProfileDto;
import com.andaily.zhishifenzi.service.UserService;
import com.andaily.zhishifenzi.web.validator.MyProfileDtoValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("/b/my_profile.zsfz")
public class MyProfileController {


    @Autowired
    private UserService userService;
    @Autowired
    private MyProfileDtoValidator validator;

    @RequestMapping(method = RequestMethod.GET)
    public String showProfile(Model model) {
        MyProfileDto formDto = userService.loadMyProfileDto();
        model.addAttribute("formDto", formDto);
        return "my_profile";
    }

    @RequestMapping(method = RequestMethod.POST)
    public String update(@ModelAttribute("formDto") MyProfileDto formDto, BindingResult result) {
        validator.validate(formDto, result);
        if (result.hasErrors()) {
            return "my_profile";
        }
        userService.updateMyProfile(formDto);
        return "redirect:my_profile.zsfz?alert=updateSuccess";
    }

}

src/main/webapp/WEB-INF/jsp/change_password.jsp

<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>修改密码</title>
</head>
<body>

<div class="row">
    <div class="col-md-12">
        <form:form commandName="changePasswordDto" id="changePasswordDtoForm">
            <div class="panel panel-primary">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="alert alert-warning">
                            <strong>注意:</strong> 修改密码成功后请重新登录系统.
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="username">登录名</label><form:input path="username" id="username"
                                                                     placeholder="请输入登录名" size="30"
                                                                     cssClass="form-control" disabled="true"
                                                                     maxlength="255" required="true"/>
                    </div>
                    <div class="form-group">
                        <label for="oldPassword">旧密码</label>
                        <form:password path="oldPassword" id="oldPassword" placeholder="请输入旧密码" maxlength="255"
                                       size="50" cssClass="form-control" required="true"/>
                        <form:errors path="oldPassword" cssClass="text-danger"/>
                    </div>
                    <div class="form-group">
                        <label for="newPassword">新密码</label>
                        <form:password path="newPassword" id="newPassword" placeholder="新密码, 长度至少6位" title="新密码, 长度至少6位"
                                       maxlength="255"
                                       size="50" cssClass="form-control" required="true"/>
                        <form:errors path="newPassword" cssClass="text-danger"/>
                    </div>

                    <div class="form-group">
                        <label for="confirmPassword">确认密码</label>
                        <form:password path="confirmPassword" id="confirmPassword" placeholder="请再次输入密码" title="请再次输入密码"
                                       maxlength="255" cssClass="form-control"
                                       size="50" required="true"/>
                        <form:errors path="confirmPassword" cssClass="text-danger"/>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i> 修改
                        </button>
                        &nbsp;<a href="index.zsfz">取消</a>
                    </div>
                </div>
            </div>
        </form:form>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/login.jsp

<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <c:set var="contextPath" value="${pageContext.request.contextPath}" scope="application"/>
    <link rel="shortcut icon" type="image/x-icon" href="${contextPath}/resources/images/favicon.ico"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <meta name="keywords" content="足球,踢足球,足球队,知识分子足球队,我们的足球,业余足球,成都业余足球队"/>
    <meta name="description" content="我们是知识分子,争先恐后接球,知识分子足球队,我们在一起欢乐的足球时光"/>
    <meta name="author" content="李胜钊,monkeyk"/>

    <title>登录 - 知识分子足球队</title>

    <link rel="stylesheet" href="${contextPath}/resources/css/bootstrap.min.css">
    <style>
        body {
            font-family: "微软雅黑", Helvetica, Verdana, Arial, sans-serif;
        }

        .login-row {
            padding-top: 12%;
        }

        .login-row .panel {
            background-color: #eeeeee;
        }

        .login-form {
            margin: 15px;
        }

        .logo-area img {
            margin-top: 25px;
            max-width: 220px;
            opacity: 0.8;
        }

    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
    <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

</head>
<body>
<c:set var="loginError" value="${param.error == '1'}"/>
<c:set var="accessError" value="${param.error == '2'}"/>


<div class="container">
    <div class="row login-row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="row">
                    <div class="col-md-6">
                        <div class="logo-area text-center">
                            <a href="${contextPath}">
                                <img src="${contextPath}/resources/images/3.jpg"
                                     title="知识分子足球队" class="img-circle" alt="zsfz"/>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form role="form" action="${contextPath}/signin" method="post" class="login-form">
                            <div class="form-group ${loginError?'has-error':''}">
                                <label for="username" class="control-label">用户</label>
                                <input type="text" class="form-control" id="username" value="${username}"
                                       placeholder="请输入用户" name="j_username" required="required"/>
                            </div>
                            <div class="form-group ${loginError?'has-error':''}">
                                <label for="password" class="control-label">密码</label>
                                <input type="password" class="form-control" id="password" name="j_password"
                                       placeholder="请输入密码" required="required"/>
                            </div>
                            <div class="checkbox">
                                <label class="text-warning">
                                    <input type="checkbox" name="_spring_security_remember_me"/> 记住用户
                                </label>
                            </div>
                            <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-hand-right"></i>
                                登录
                            </button>
                            &nbsp;
                            <span class="text-danger">
                                <c:if test="${loginError}">
                                    <i class="glyphicon glyphicon-warning-sign"></i> 登录失败, 请检查.
                                </c:if>
                                <c:if test="${accessError}">
                                    <i class="glyphicon glyphicon-warning-sign"></i> 访问被拒绝, 请检查.
                                </c:if>
                            </span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p class="text-muted text-center">&copy; 2008-2015 知识分子足球队 All rights reserved.</p>
        </div>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/match_photos.jsp

<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<c:if test="${not empty photosDto.photos}">
    <h2>比赛照片</h2>

    <div class="pictures-area">
        <div class="row">
            <c:forEach items="${photosDto.photos}" var="p" varStatus="s">
            <div class="col-md-3">
                <a href="${contextPath}/public/image/${p.guid}.zsfz" class="pictureGroup">
                    <img data-original="${contextPath}/public/image/${p.guid}.zsfz?w=180" alt="..."
                         src="${contextPath}/resources/images/loading.gif"
                         class="img-thumbnail lazy"/>
                </a>
            </div>
            <c:if test="${s.count%4 eq 0}">
        </div>
        <div class="row" style="margin-top:5px;">
            </c:if>
            </c:forEach>

        </div>
    </div>


    <script src="${contextPath}/resources/colorbox/jquery.colorbox-min.js"></script>
    <script src="${contextPath}/resources/colorbox/jquery.colorbox-zh-CN.js"></script>
    <script src="${contextPath}/resources/js/jquery.lazyload.min.js"></script>

    <script type="text/javascript">
        $(function () {
            //colorbox init
            $(".pictures-area a").colorbox({
                maxWidth:'80%',
                rel:'pictureGroup',
                photo:true
            });
            $("img.lazy").lazyload({
                effect:"fadeIn",
                threshold:10
            });
        });
    </script>
    <hr/>
</c:if>

src/main/webapp/WEB-INF/jsp/my_profile.jsp

<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>更新信息</title>
    <link rel="stylesheet" href="${contextPath}/resources/css/datepicker.css"/>
</head>
<body>

<div class="row">
    <div class="col-md-12">
        <!--// alert start -->
        <div class="alert alert-success hide">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><i class="glyphicon glyphicon-ok"></i>
                <span id="updateSuccess" class="hide">更新个人信息成功!</span>
            </div>
        </div>
        <c:if test="${not formDto.enabled}">
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <div><i class="glyphicon glyphicon-warning-sign"></i>
                    <span>你的角色是非球员, 不能修改个人信息!</span>
                </div>
            </div>
        </c:if>
        <!--// alert end -->
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <form:form commandName="formDto" id="profileForm" action="${contextPath}/b/my_profile.zsfz">
            <form:hidden path="enabled"/>
            <div class="panel panel-primary">
                <div class="panel-body">
                    <div class="form-group">
                        <label for="fullName">姓名</label><form:input path="fullName" id="fullName"
                                                                    placeholder="请输入用户姓名" size="30"
                                                                    cssClass="form-control"
                                                                    maxlength="255" required="true"/>
                        <form:errors path="fullName" cssClass="text-danger"/>
                        <p class="help-block">你的尊姓大名.</p>
                    </div>
                    <div class="form-group">
                        <label for="number" class="control-label">球衣号码</label>
                        <form:input path="number" cssClass="form-control" id="number" placeholder="请输入球衣号码"
                                    required="required"/>
                        <form:errors path="number" cssClass="text-danger"/>
                        <p class="help-block">我的球衣号码.</p>
                    </div>
                    <div class="form-group">
                        <label for="email">邮件地址</label><form:input path="email" id="email"
                                                                   placeholder="请输入邮件地址" size="30"
                                                                   cssClass="form-control" required="true"
                                                                   maxlength="255"/>
                        <form:errors path="email" cssClass="text-danger"/>
                        <p class="help-block">球队有的信息会通过发送邮件通知.</p>
                    </div>
                    <div class="form-group">
                        <label for="phone">联系电话</label><form:input path="phone" id="phone"
                                                                   placeholder="请输入联系电话"
                                                                   cssClass="form-control"
                                                                   maxlength="255"/>
                        <form:errors path="phone" cssClass="text-danger"/>
                        <p class="help-block">方便大家联系.</p>
                    </div>
                    <div class="form-group">
                        <label for="entryDate">加入球队日期</label><form:input path="entryDate" id="entryDate"
                                                                         placeholder="请选择加入球队日期"
                                                                         cssClass="form-control"
                                                                         maxlength="255"/>
                        <form:errors path="entryDate" cssClass="text-danger"/>
                        <p class="help-block">若不清楚具体的日期就选择一个大概的日期啦.</p>
                    </div>
                    <div class="form-group">
                        <label for="birthday">生日日期</label><form:input path="birthday" id="birthday"
                                                                      placeholder="请选择我的生日日期"
                                                                      cssClass="form-control"
                                                                      maxlength="255"/>
                        <form:errors path="birthday" cssClass="text-danger"/>
                        <p class="help-block">这个日期不会记错吧.</p>
                    </div>
                    <div class="form-group">
                        <label for="description" class="control-label">自我描述</label>
                        <form:textarea path="description" id="description" class="form-control" rows="3"
                                       placeholder="写点自我描述吧"/>
                        <form:errors path="description" cssClass="text-danger"/>
                        <p class="help-block">自我描述, 如你的兴趣,学历等等你想告诉我们的.</p>
                    </div>
                    <div class="form-group">
                        <c:if test="${formDto.enabled}">
                            <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i> 保存
                            </button>
                        </c:if>
                        &nbsp;<a href="index.zsfz">返回</a>
                    </div>
                </div>
            </div>
        </form:form>
    </div>
</div>

<script src="${contextPath}/resources/js/datepicker/bootstrap-datepicker.js"></script>
<script src="${contextPath}/resources/js/datepicker/bootstrap-datepicker.zh-CN.js"></script>

<script>
    $(function () {
        new MyProfile('${param.alert}');
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/player_info.jsp

<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div>
    <div class="row">
        <div class="col-md-6">
            <img src="${contextPath}/public/player_image/${playerDto.guid}.zsfz" style="width: 97px;height: 120px;"
                 alt="img" class="thumbnail"/>
        </div>
        <div class="col-md-6">
            <strong>${playerDto.number}</strong>号 <br/>
            <span class="text-muted">位置:</span> ${playerDto.position.label} <br/>

            <p class="text-info">
                ${playerDto.description}
            </p>
        </div>
    </div>
</div>