src/main/java/com/andaily/zhishifenzi/domain/dto/match/GoalDto.java
package com.andaily.zhishifenzi.domain.dto.match;

import com.andaily.zhishifenzi.domain.dto.AbstractDto;
import com.andaily.zhishifenzi.domain.dto.player.PlayerDto;
import com.andaily.zhishifenzi.domain.match.Goal;
import com.andaily.zhishifenzi.domain.player.Player;

import java.util.ArrayList;
import java.util.List;

/**
 * 14-3-31 下午10:38
 *
 * @author Shengzhao Li
 */
public class GoalDto extends AbstractDto {

    //进球队员
    protected PlayerDto goalPlayer;
    //助攻队员
    protected PlayerDto assistantPlayer;
    //对方OG ,乌龙球
    protected boolean ownGoal;
    //进球时间
    protected int goalTime;

    public GoalDto() {
    }

    public GoalDto(Goal goal) {
        super(goal.guid());
        this.ownGoal = goal.ownGoal();
        this.goalTime = goal.goalTime();
        if (!this.ownGoal) {
            this.goalPlayer = new PlayerDto(goal.goalPlayer());

            Player assistantPlayer = goal.assistantPlayer();
            if (assistantPlayer != null) {
                this.assistantPlayer = new PlayerDto(assistantPlayer);
            }
        }
    }

    public PlayerDto getGoalPlayer() {
        return goalPlayer;
    }

    public void setGoalPlayer(PlayerDto goalPlayer) {
        this.goalPlayer = goalPlayer;
    }

    public PlayerDto getAssistantPlayer() {
        return assistantPlayer;
    }

    public void setAssistantPlayer(PlayerDto assistantPlayer) {
        this.assistantPlayer = assistantPlayer;
    }

    public boolean isOwnGoal() {
        return ownGoal;
    }

    public void setOwnGoal(boolean ownGoal) {
        this.ownGoal = ownGoal;
    }

    public int getGoalTime() {
        return goalTime;
    }

    public void setGoalTime(int goalTime) {
        this.goalTime = goalTime;
    }

    public static List<GoalDto> toDtos(List<Goal> goals) {
        List<GoalDto> dtos = new ArrayList<>(goals.size());
        for (Goal goal : goals) {
            dtos.add(new GoalDto(goal));
        }
        return dtos;
    }
}

src/main/java/com/andaily/zhishifenzi/domain/dto/match/MatchDetailsDto.java
package com.andaily.zhishifenzi.domain.dto.match;

import com.andaily.zhishifenzi.domain.match.Match;

/**
 * @author Shengzhao Li
 */
public class MatchDetailsDto extends MatchDto {


    public MatchDetailsDto() {
        super();
    }

    public MatchDetailsDto(Match match) {
        super(match, true);
    }

    //2014-03-01 10:30 [3:1] VS 电脑城足球队
    public String getTitle() {
        StringBuilder sb = new StringBuilder();
        return sb.append(matchTime).append(" [")
                .append(homeScores).append(":").append(awayScores)
                .append("]  VS ").append(opponent.getName()).toString();
    }
}

src/main/java/com/andaily/zhishifenzi/domain/dto/match/MatchDto.java
package com.andaily.zhishifenzi.domain.dto.match;

import com.andaily.zhishifenzi.domain.dto.AbstractDto;
import com.andaily.zhishifenzi.domain.dto.club.ClubDto;
import com.andaily.zhishifenzi.domain.dto.player.PlayerDto;
import com.andaily.zhishifenzi.domain.dto.stadium.StadiumDto;
import com.andaily.zhishifenzi.domain.match.Match;
import com.andaily.zhishifenzi.domain.match.MatchPlayer;
import com.andaily.zhishifenzi.infrastructure.DateUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * 14-3-31 下午10:03
 *
 * @author Shengzhao Li
 */
public class MatchDto extends AbstractDto {

    //时间
    protected String matchTime;

    //主队进球
    protected int homeScores;
    //客队进球数
    protected int awayScores;
    /**
     * 选择该比赛的预告信息,
     * 若选择则对手,时间与场地的信息从它获取
     */
    protected MatchNoticeDto notice;

    //赛季
    protected SeasonDto season;

    //对手
    protected ClubDto opponent;
    //场地
    protected StadiumDto stadium;

    //进球信息
    protected List<GoalDto> goals = new ArrayList<>();

    //比赛队员
    protected List<PlayerDto> players = new ArrayList<>();

    //备注,总结信息
    protected String remark;
    //五人制
    protected boolean futsal;

    public MatchDto() {
    }

    public MatchDto(Match match) {
        this(match, false);
    }

    public MatchDto(Match match, boolean full) {
        super(match.guid());
        this.matchTime = DateUtils.toDateTime(match.matchTime());
        this.homeScores = match.homeScores();
        this.awayScores = match.awayScores();

        this.notice = match.notice() != null ? new MatchNoticeDto(match.notice()) : null;
        this.season = new SeasonDto(match.season());
        this.opponent = new ClubDto(match.opponent());

        this.stadium = new StadiumDto(match.stadium());
        this.remark = match.remark();
        this.futsal = match.futsal();

        if (full) {
            this.goals = GoalDto.toDtos(match.goals());
            List<MatchPlayer> matchPlayers = match.players();
            for (MatchPlayer matchPlayer : matchPlayers) {
                this.players.add(new PlayerDto(matchPlayer.player()));
            }
        }
    }

    public int getMatchPlayersSize() {
        return this.players.size();
    }

    public String getGoalPlayerNames() {
        StringBuilder sb = new StringBuilder();
        for (GoalDto goal : goals) {
            if (goal.isOwnGoal()) {
                sb.append("OG,");
            } else {
                sb.append(goal.getGoalPlayer().getFullName());
                PlayerDto assistantPlayer = goal.getAssistantPlayer();
                if (assistantPlayer != null) {
                    sb.append("(").append(assistantPlayer.getFullName()).append(")");
                } else {
                    sb.append("(无)");
                }
                sb.append(",");
            }
        }
        if (goals.isEmpty()) {
            sb.append("----");
        }
        int length = sb.length();
        return length > 0 ? sb.toString().substring(0, length - 1) : sb.toString();
    }

    public String getMatchTime() {
        return matchTime;
    }

    public void setMatchTime(String matchTime) {
        this.matchTime = matchTime;
    }

    public int getHomeScores() {
        return homeScores;
    }

    public void setHomeScores(int homeScores) {
        this.homeScores = homeScores;
    }

    public int getAwayScores() {
        return awayScores;
    }

    public void setAwayScores(int awayScores) {
        this.awayScores = awayScores;
    }

    public MatchNoticeDto getNotice() {
        return notice;
    }

    public void setNotice(MatchNoticeDto notice) {
        this.notice = notice;
    }

    public SeasonDto getSeason() {
        return season;
    }

    public void setSeason(SeasonDto season) {
        this.season = season;
    }

    public ClubDto getOpponent() {
        return opponent;
    }

    public void setOpponent(ClubDto opponent) {
        this.opponent = opponent;
    }

    public StadiumDto getStadium() {
        return stadium;
    }

    public void setStadium(StadiumDto stadium) {
        this.stadium = stadium;
    }

    public List<GoalDto> getGoals() {
        return goals;
    }

    public int getGoalsSize() {
        return goals.size();
    }

    public void setGoals(List<GoalDto> goals) {
        this.goals = goals;
    }

    public List<PlayerDto> getPlayers() {
        return players;
    }

    public void setPlayers(List<PlayerDto> players) {
        this.players = players;
    }

    public String getRemark() {
        return remark;
    }

    public String getShortRemark() {
        if (remark != null && remark.length() > 20) {
            return remark.substring(0, 20) + "...";
        }
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public boolean isFutsal() {
        return futsal;
    }

    public void setFutsal(boolean futsal) {
        this.futsal = futsal;
    }

    public static List<MatchDto> toDtos(List<Match> matches, boolean full) {
        List<MatchDto> dtos = new ArrayList<>(matches.size());
        for (Match match : matches) {
            dtos.add(new MatchDto(match, full));
        }
        return dtos;
    }
}

src/main/java/com/andaily/zhishifenzi/domain/dto/match/MatchFormDto.java
package com.andaily.zhishifenzi.domain.dto.match;

import com.andaily.zhishifenzi.domain.commons.Photo;
import com.andaily.zhishifenzi.domain.dto.club.ClubDto;
import com.andaily.zhishifenzi.domain.dto.stadium.StadiumDto;
import com.andaily.zhishifenzi.domain.match.Match;
import com.andaily.zhishifenzi.domain.match.MatchPlayer;
import com.andaily.zhishifenzi.infrastructure.DateUtils;
import com.andaily.zhishifenzi.infrastructure.MatchUtils;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 14-4-3 下午11:42
 *
 * @author Shengzhao Li
 */
public class MatchFormDto extends MatchDto {

    private List<MatchNoticeDto> notices = new ArrayList<>();
    private List<StadiumDto> stadiums = new ArrayList<>();
    private List<ClubDto> clubs = new ArrayList<>();

    private List<SeasonDto> seasons = new ArrayList<>();

    private List<String> joinPlayerGuids = new ArrayList<>();

    //比赛照片
    private List<MultipartFile> photos = new ArrayList<>();

    public MatchFormDto() {
        super();
    }

    public MatchFormDto(Match match) {
        super(match, true);

        List<MatchPlayer> matchPlayers = match.players();
        for (MatchPlayer matchPlayer : matchPlayers) {
            joinPlayerGuids.add(matchPlayer.player().guid());
        }
    }

    public MatchFormDto(String guid) {
        this.guid = guid;
    }

    public List<String> getJoinPlayerGuids() {
        return joinPlayerGuids;
    }

    public void setJoinPlayerGuids(List<String> joinPlayerGuids) {
        this.joinPlayerGuids = joinPlayerGuids;
    }

    public boolean isNewly() {
        return super.isNewly() || MatchUtils.isCreate(guid);
    }

    public List<MatchNoticeDto> getNotices() {
        return notices;
    }

    public void setNotices(List<MatchNoticeDto> notices) {
        this.notices = notices;
    }

    public List<StadiumDto> getStadiums() {
        return stadiums;
    }

    public void setStadiums(List<StadiumDto> stadiums) {
        this.stadiums = stadiums;
    }

    public List<ClubDto> getClubs() {
        return clubs;
    }

    public void setClubs(List<ClubDto> clubs) {
        this.clubs = clubs;
    }

    public List<SeasonDto> getSeasons() {
        return seasons;
    }

    public void setSeasons(List<SeasonDto> seasons) {
        this.seasons = seasons;
    }

    public Match toDomain(Match match) {
        return match.remark(remark)
                .homeScores(homeScores)
                .awayScores(awayScores)
                .futsal(futsal)
                .matchTime(DateUtils.getDate(matchTime, DateUtils.DATE_TIME_FORMAT));
    }

    public List<MultipartFile> getPhotos() {
        return photos;
    }

    public void setPhotos(List<MultipartFile> photos) {
        this.photos = photos;
    }

    public List<Photo> generatePhotos() {
        List<Photo> photoList = new ArrayList<>();
        for (MultipartFile photo : photos) {
            if (photo != null && !photo.isEmpty()) {
                try {
                    Photo photo1 = new Photo(photo.getOriginalFilename(), photo.getBytes());
                    photoList.add(photo1);
                } catch (IOException e) {
                    throw new IllegalStateException(e);
                }
            }
        }
        return photoList;
    }
}

src/main/java/com/andaily/zhishifenzi/domain/dto/match/MatchMainDto.java
package com.andaily.zhishifenzi.domain.dto.match;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Shengzhao Li
 */
public class MatchMainDto extends MatchListDto {


    private int totalScores;//总进球
    private int totalConceded; //总失球
    private int totalAssistants;//总助攻
    private int totalOwnGoal;

    private int winCount;
    private int eqCount;
    private int failCount;

    private List<MatchNoticeDto> notices = new ArrayList<>();

    public MatchMainDto() {
    }

    public int getTotalScores() {
        return totalScores;
    }

    public MatchMainDto setTotalScores(int totalScores) {
        this.totalScores = totalScores;
        return this;
    }

    public int getTotalConceded() {
        return totalConceded;
    }

    public MatchMainDto setTotalConceded(int totalConceded) {
        this.totalConceded = totalConceded;
        return this;
    }

    public int getTotalAssistants() {
        return totalAssistants;
    }

    public MatchMainDto setTotalAssistants(int totalAssistants) {
        this.totalAssistants = totalAssistants;
        return this;
    }

    public int getWinCount() {
        return winCount;
    }

    public MatchMainDto setWinCount(int winCount) {
        this.winCount = winCount;
        return this;
    }

    public int getEqCount() {
        return eqCount;
    }

    public MatchMainDto setEqCount(int eqCount) {
        this.eqCount = eqCount;
        return this;
    }

    public int getFailCount() {
        return failCount;
    }

    public MatchMainDto setFailCount(int failCount) {
        this.failCount = failCount;
        return this;
    }

    public int getTotalOwnGoal() {
        return totalOwnGoal;
    }

    public MatchMainDto setTotalOwnGoal(int totalOwnGoal) {
        this.totalOwnGoal = totalOwnGoal;
        return this;
    }

    public List<MatchNoticeDto> getNotices() {
        return notices;
    }

    public MatchMainDto setNotices(List<MatchNoticeDto> notices) {
        this.notices = notices;
        return this;
    }
}

src/main/java/com/andaily/zhishifenzi/domain/dto/match/MatchNoticeDto.java
package com.andaily.zhishifenzi.domain.dto.match;

import com.andaily.zhishifenzi.domain.club.Club;
import com.andaily.zhishifenzi.domain.dto.AbstractDto;
import com.andaily.zhishifenzi.domain.dto.club.ClubDto;
import com.andaily.zhishifenzi.domain.dto.stadium.StadiumDto;
import com.andaily.zhishifenzi.domain.match.MatchNotice;
import com.andaily.zhishifenzi.domain.stadium.Stadium;
import com.andaily.zhishifenzi.infrastructure.DateUtils;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * 14-3-21 下午9:21
 *
 * @author Shengzhao Li
 */
public class MatchNoticeDto extends AbstractDto {



    //时间
    protected String time;
    protected String previewTime;
    //场地
    protected StadiumDto stadium;
    //对手
    protected ClubDto opponent;
    //备注
    protected String remark;
    //是否激活,激活则在首页显示提示
    //可同时激活多个
    protected boolean pending;

    //比赛时间是否已过去
    protected boolean pastTime;

    public MatchNoticeDto() {
    }

    public MatchNoticeDto(MatchNotice notice) {
        super(notice.guid());
        Date time1 = notice.time();
        this.time = DateUtils.toDateTime(time1);
        this.pastTime = time1.before(DateUtils.now());
        this.previewTime = DateUtils.toDateText(time1, MatchNotice.DATE_WEEK_FORMAT);

        this.stadium = new StadiumDto(notice.stadium());
        this.opponent = new ClubDto(notice.opponent());
        this.remark = notice.remark();
        this.pending = notice.pending();
    }

    //3月2日，10：00，太平寺 4 号场地，对手：昌达足球队。穿新球衣。
    public String getPreviewText() {
        StringBuilder sb = new StringBuilder();
        sb.append(previewTime).append("，  ")
                .append(stadium.getName()).append("， 对手:  ")
                .append(opponent.getName()).append("。")
                .append(remark);
        return sb.toString();
    }

    public String getPreviewTime() {
        return previewTime;
    }

    public void setPreviewTime(String previewTime) {
        this.previewTime = previewTime;
    }

    public boolean isPastTime() {
        return pastTime;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public StadiumDto getStadium() {
        return stadium;
    }

    public void setStadium(StadiumDto stadium) {
        this.stadium = stadium;
    }

    public ClubDto getOpponent() {
        return opponent;
    }

    public void setOpponent(ClubDto opponent) {
        this.opponent = opponent;
    }

    public String getRemark() {
        return remark;
    }

    public String getShortRemark() {
        if (remark != null && remark.length() > 30) {
            return remark.substring(0, 30) + "...";
        }
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public boolean isPending() {
        return pending;
    }

    public void setPending(boolean pending) {
        this.pending = pending;
    }

    public static List<MatchNoticeDto> toDtos(List<MatchNotice> notices) {
        List<MatchNoticeDto> dtos = new ArrayList<>(notices.size());
        for (MatchNotice notice : notices) {
            dtos.add(new MatchNoticeDto(notice));
        }
        return dtos;
    }
}

src/main/webapp/WEB-INF/jsp/backend/match/match_details.jsp

<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>比赛明细</title>
    <link rel="stylesheet" href="${contextPath}/resources/colorbox/colorbox.css"/>

    <style>
        .goal-ul li {
            margin-left: 20px;
        }

        .pictures-area a img {
            max-width: 180px;
            max-height: 140px;
        }
    </style>
</head>
<body>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                比赛明细
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    <c:if test="${not empty detailsDto.notice}">
                        <li class="list-group-item">
                        <span class="text-muted"><i
                                class="glyphicon glyphicon-calendar"></i> 比赛预告: </span>
                            <i>${detailsDto.notice.previewText}</i>
                        </li>
                    </c:if>
                    <li class="list-group-item">
                        <span class="text-muted"><i
                                class="glyphicon glyphicon-calendar"></i> 比赛时间: </span> ${detailsDto.matchTime}
                    </li>
                    <li class="list-group-item">
                        <span class="text-muted"><i class="glyphicon glyphicon-hand-right"></i> 比赛对手: </span> <a
                            href="javascript:void(0)">${detailsDto.opponent.name}</a>
                    </li>
                    <li class="list-group-item">
                        <h3 class="list-group-item-heading">
                            <span class="text-muted"><i class="glyphicon glyphicon-pushpin"></i> 比分: </span>
                            <c:if test="${detailsDto.homeScores > detailsDto.awayScores}">
                                <strong class="text-danger">${detailsDto.homeScores}:${detailsDto.awayScores}</strong>
                            </c:if>
                            <c:if test="${detailsDto.homeScores eq detailsDto.awayScores}">
                                <strong class="text-muted">${detailsDto.homeScores}:${detailsDto.awayScores}</strong>
                            </c:if>
                            <c:if test="${detailsDto.homeScores <detailsDto.awayScores}">
                                <strong class="text-warning">${detailsDto.homeScores}:${detailsDto.awayScores}</strong>
                            </c:if>
                        </h3>

                        <div class="list-group-item-text">
                            <ul class="list-unstyled goal-ul">
                                <c:forEach items="${detailsDto.goals}" var="g" varStatus="s">
                                    <li>
                                        <img src="${contextPath}/resources/images/football_1.png"
                                             class="img-responsive pull-left" style="max-width: 16px;"/>&nbsp;
                                        <c:if test="${g.goalTime > -1}">
                                            第 ${g.goalTime} 分钟,
                                        </c:if>
                                        <c:if test="${g.ownGoal}">
                                            对手OG
                                        </c:if>
                                        <c:if test="${not g.ownGoal}">
                                            <a href="javascript:void(0)">${g.goalPlayer.fullName}</a> 进球, <a
                                                href="javascript:void(0)">${empty g.assistantPlayer.fullName?'无':g.assistantPlayer.fullName}</a> 助攻.
                                        </c:if>
                                    </li>
                                </c:forEach>
                            </ul>

                        </div>
                    </li>
                    <li class="list-group-item">
                        <span class="text-muted"><i class="glyphicon glyphicon-tower"></i> 比赛球场: </span> <a
                            href="javascript:void(0)">${detailsDto.stadium.name}</a>
                    </li>
                    <li class="list-group-item">
                        <span class="text-muted"><i class="glyphicon glyphicon-th"></i> 赛季: </span> <a
                            href="javascript:void(0)">${detailsDto.season.name}</a>
                    </li>
                    <li class="list-group-item">
                        <span class="text-muted"><i class="glyphicon glyphicon-user"></i> 参赛球员: </span>
                        <c:forEach items="${detailsDto.players}" var="p" varStatus="s">
                            <a href="javascript:void(0)">${p.fullName}</a>&nbsp;
                        </c:forEach>
                    </li>
                    <li class="list-group-item">
                        <span class="text-muted"><i class="glyphicon glyphicon-pencil"></i> 比赛备注: </span> <a
                            href="javascript:void(0)">${detailsDto.remark}</a>
                    </li>
                    <c:if test="${detailsDto.futsal}">
                        <li class="list-group-item">
                            <h4 class="text-danger"><i class="glyphicon glyphicon-star-empty"></i> 这是一场五人制足球赛.</h4>
                        </li>
                    </c:if>
                </ul>
                <div id="matchPhotos" guid="${detailsDto.guid}"></div>
                <p class="text-center">
                    <a href="javascript:history.back();" class="btn btn-info">&laquo; 返回</a>
                </p>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        new MatchDetails();
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/backend/match/match_notice_form.jsp

<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE html>
<html>
<head>
    <title>比赛预告</title>
    <link rel="stylesheet" href="${contextPath}/resources/css/bootstrap-datetimepicker.min.css"/>
</head>
<body>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-danger">
            <div class="panel-body">
                <form:form commandName="formDto" role="form">
                    <div class="form-group">
                        <label for="time" class="control-label">比赛时间</label>
                        <form:input path="time" cssClass="form-control" id="time" placeholder="请选择比赛时间"
                                    required="required"/>
                        <form:errors path="time" cssClass="text-danger"/>
                        <p class="help-block">比赛时间必须在现在之后.</p>
                    </div>
                    <div class="form-group">
                        <label for="stadiumGuid" class="control-label">比赛球场</label>
                        <form:select path="stadium.guid" id="stadiumGuid" cssClass="form-control">
                            <form:option value="" label="选择比赛球场"/>
                            <form:options items="${formDto.stadiums}" itemLabel="nameIncludeHome" itemValue="guid"/>
                        </form:select>
                        <form:errors path="stadium.guid" cssClass="text-danger"/>
                        <p class="help-block">选择比赛在哪球场踢, 若没有对应的球场则点击'球场'菜单去添加.</p>
                    </div>
                    <div class="form-group">
                        <label for="opponentGuid" class="control-label">比赛对手</label>
                        <form:select path="opponent.guid" id="opponentGuid" cssClass="form-control">
                            <form:option value="" label="选择比赛对手"/>
                            <form:options items="${formDto.clubs}" itemLabel="name" itemValue="guid"/>
                        </form:select>
                        <form:errors path="opponent.guid" cssClass="text-danger"/>
                        <p class="help-block">选择比赛和谁踢, 若没有对应的对手则点击'对手'菜单去添加.</p>
                    </div>
                    <div class="form-group">
                        <label for="remark" class="control-label">备注信息</label>
                        <form:textarea path="remark" id="remark" class="form-control" rows="3"
                                       placeholder="关于该比赛预告的其他信息, 在这儿输入." required="true"/>
                        <form:errors path="remark" cssClass="text-danger"/>
                        <p class="help-block">比赛预告的其他信息.</p>
                    </div>

                    <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> 保存
                    </button>
                    &nbsp;<a href="../../match_notice.zsfz">取消</a>

                </form:form>
            </div>
        </div>
    </div>
</div>

<script src="${contextPath}/resources/js/datepicker/bootstrap-datetimepicker.min.js"></script>
<script src="${contextPath}/resources/js/datepicker/bootstrap-datetimepicker.zh-CN.js"></script>

<script>
    $(function () {
        new MatchNoticeForm('${startTime}');
    });
</script>
</body>
</html>